apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: demo-git
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.com/felixtran39/demo
---

apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: push-loc
spec:
  type: image
  params:
    - name: url
      value: gcr.io/yuwenma-gke-playground/pl-test-img

---

apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: build
spec:
  params:
    - name: pathToDockerFile
      type: string
      description: The path to the dockerfile to build
      default: /workspace/docker-source/Dockerfile
    - name: pathToContext
      type: string
      description:
        The build context used by Kaniko
        (https://github.com/GoogleContainerTools/kaniko#kaniko-build-contexts)
      default: /workspace/docker-source
  resources:
    inputs:
      - name: docker-source
        type: git
    outputs:
      - name: builtImage
        type: image
  steps:
    - name: cloning
      image: gcr.io/cloud-builders/git
      command:
              - git
      args:
              - clone
              - https://github.com/felixtran39/demo.git
              - /repo/demo
      volumeMounts:
              - name: repo
                mountPath: /repo
    - name: kustomizing
      image: gcr.io/yuwenma-gke-playground/kustomize
      command:
              - kustomize
      args:
              - build
              - "git::https://github.com/felixtran39/tekton.git"
              - "-o"
              - /repo/demo/skaffold.yaml
      volumeMounts:
              - name: repo
                mountPath: /repo
    - name: build-and-push
      image: gcr.io/k8s-skaffold/skaffold:v1.11.0
      # specifying DOCKER_CONFIG is required to allow kan
      # iko to detect docker credential
      env:
        - name: "DOCKER_CONFIG"
          value: "/tekton/home/.docker/"
      workingDir: /repo/demo
      command:
        - skaffold
      args:
        - build
      env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /secret/kaniko-secret.json
      volumeMounts:
        - name: kaniko-secret
          mountPath: /secret
        - name: repo
          mountPath: /repo
  volumes:
    - name: kaniko-secret
      secret:
        secretName: kaniko-secret
    - name: repo
      emptyDir: {} 

---

apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: build-run
spec:
  taskRef:
    name: build
  params:
    - name: pathToDockerFile
      value: /workspace/docker-source/Dockerfile
    - name: pathToContext
      value: /workspace/docker-source #configure: may change according to your source
  resources:
    inputs:
      - name: docker-source
        resourceRef:
          name: demo-git
    outputs:
      - name: builtImage
        resourceRef:
          name: push-loc
