apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: app-repo
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.com/felixtran39/demo
---

apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: build
spec:
  resources:
    inputs:
      - name: app-repo
        type: git
  steps:
    - name: cloning
      image: gcr.io/cloud-builders/git
      command:
              - git
      args:
              - clone
              - $(resources.inputs.app-repo.url)
              - /repo/demo
      volumeMounts:
              - name: repo
                mountPath: /repo
    - name: kustomizing
      image: gcr.io/yuwenma-gke-playground/kustomize
      command:
              - kustomize
      args:
              - build
              - "git::https://github.com/felixtran39/tekton.git"
              - "-o"
              - /repo/demo/skaffold.yaml
      volumeMounts:
              - name: repo
                mountPath: /repo
    - name: build-and-push
      image: gcr.io/k8s-skaffold/skaffold:v1.11.0
      # specifying DOCKER_CONFIG is required to allow kan
      # iko to detect docker credential
      env:
        - name: "DOCKER_CONFIG"
          value: "/tekton/home/.docker/"
      workingDir: /repo/demo
      command:
        - skaffold
      args:
        - build
      env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /secret/kaniko-secret.json
      volumeMounts:
        - name: kaniko-secret
          mountPath: /secret
        - name: repo
          mountPath: /repo
  volumes:
    - name: kaniko-secret
      secret:
        secretName: kaniko-secret
    - name: repo
      emptyDir: {} 

---

apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: build-run
spec:
  taskRef:
    name: build
  resources:
    inputs:
      - name: app-repo
        resourceRef:
          name: app-repo
